name: Generate Snake Contribution Graph 🐍

on:
  # Automatic trigger at 00:00 every day (UTC)
  schedule:
    - cron: "0 0 * * *"
    
  # Manual trigger in the GitHub Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Snake generator from Platane's repo
      - name: Generate Snake SVG
        uses: Platane/snk@master
        with:
          github_user_name: shree-bot
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push the snake SVGs to the output branch
      - name: Push snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
